"""init

Revision ID: 8bfd44484520
Revises: 
Create Date: 2026-05-18 22:47:00.037785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bfd44484520'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kantin',
    sa.Column('kantin_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('alamat', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('kantin_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('nomor_telepon', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mahasiswa',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('nim', sa.String(), nullable=False),
    sa.Column('fakultas', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('nim')
    )
    op.create_table('toko',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kantin_id', sa.Integer(), nullable=False),
    sa.Column('foto', sa.Integer(), nullable=False),
    sa.Column('tanggal_diajukan', sa.DateTime(), nullable=False),
    sa.Column('tanggal_diterima', sa.DateTime(), nullable=False),
    sa.Column('status_buka', sa.Boolean(), nullable=False),
    sa.Column('jenis_toko', sa.String(length=20), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('rating_avg', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['kantin_id'], ['kantin.kantin_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('pesanan',
    sa.Column('pesanan_id', sa.Integer(), nullable=False),
    sa.Column('mahasiswa_id', sa.Uuid(), nullable=False),
    sa.Column('toko_id', sa.Uuid(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('total_harga', sa.Integer(), nullable=False),
    sa.Column('total_bayar', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.user_id'], ),
    sa.ForeignKeyConstraint(['toko_id'], ['toko.user_id'], ),
    sa.PrimaryKeyConstraint('pesanan_id')
    )
    op.create_table('produk',
    sa.Column('produk_id', sa.Integer(), nullable=False),
    sa.Column('toko_id', sa.Uuid(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('deskripsi', sa.String(length=100), nullable=False),
    sa.Column('harga', sa.Integer(), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=False),
    sa.Column('foto', sa.String(), nullable=False),
    sa.Column('kategori', sa.String(), nullable=False),
    sa.Column('diskon_berlaku', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['toko_id'], ['toko.user_id'], ),
    sa.PrimaryKeyConstraint('produk_id')
    )
    op.create_table('detail_pesanan',
    sa.Column('dp_id', sa.Integer(), nullable=False),
    sa.Column('pesanan_id', sa.Integer(), nullable=False),
    sa.Column('produk_id', sa.Integer(), nullable=False),
    sa.Column('harga_satuan', sa.Integer(), nullable=False),
    sa.Column('jumlah_beli', sa.Integer(), nullable=False),
    sa.Column('subtotal_harga', sa.Integer(), nullable=False),
    sa.Column('catatan', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['pesanan_id'], ['pesanan.pesanan_id'], ),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.produk_id'], ),
    sa.PrimaryKeyConstraint('dp_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail_pesanan')
    op.drop_table('produk')
    op.drop_table('pesanan')
    op.drop_table('toko')
    op.drop_table('mahasiswa')
    op.drop_table('users')
    op.drop_table('kantin')
    # ### end Alembic commands ###
