"""empty message

Revision ID: 9c1a35d10351
Revises: 8bfd44484520
Create Date: 2026-05-19 10:16:34.296514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1a35d10351'
down_revision: Union[str, Sequence[str], None] = '8bfd44484520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('toko', 'foto')
    op.add_column('users', sa.Column('foto', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'foto')
    op.add_column('toko', sa.Column('foto', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
